### ISSUE TITLE
Black Screen with Hints

### ISSUE THREAD

**Issue by alkaris2** [ssrando/ssrando#501] opened 2023-11-13 11:30 UTC
When viewing Gossip Stone Hints it just shows black screen when trying to view the Gossip Stone Hint.

Using Dolphin [makepkg] 5.0-19870 on Manjaro Linux

**Comment by YourAverageLink** [comment] 2023-11-13 16:46
My guess is you're referring to the videos on the Sheikah Stone near the sparring hall. Those videos were removed to trim the file size of the randomized iso. Gossip stone hints refer to the gossip stones you would raise with the harp in vanilla. For example, there is one on the Lumpy Pumpkin.

**Comment by alkaris2** [comment] 2023-11-13 16:55
Those stones display no text but shows a text box when interacting with them.

**Comment by YourAverageLink** [comment] 2023-11-13 19:49
Which hint distribution were you using?

**Comment by lepelog** [comment] 2023-11-15 18:31
@alkaris2 Please upload the spoiler log here and also describe a way to reproduce this issue, currently we don't have enough information to reproduce this.

Which gossip stone *exactly* did you talk to that causes the issue? Does "black screen" mean some kind of crash or softlock or do you just mean the textbox is empty? Cause the empty textbox is known

**Comment by lepelog** [comment] 2024-02-21 00:08
Probably fixed by #502

I'll close this since there isn't enough information, please open a new issue with more infos if this bug persists

**Closed by lepelog** 2024-02-21 00:08 UTC
