### ISSUE TITLE
PAL version?

### ISSUE THREAD

**Issue by AimBot1711** [ssrando/ssrando#138] opened 2021-10-29 01:11 UTC
it is impossible to get the 1.00 ntsc version of SS anymore, so it would be great to have a version compatible with PAL .iso files for Dolphin.

**Comment by lepelog** [comment] 2021-11-09 21:55
The plan is to eventually patch all versions back to 1.00, see #109 . Closing this, as it's basically a duplicate of that issue, it's not forgotten though

**Closed by lepelog** 2021-11-09 21:55 UTC
